function h = render_marker(axes, p, color, marker, marker_size)
% RENDER_MARKER plots markers
%
% Author: Paulo A. Pagliosa
% Last revision: 05/09/2012
%
% Input
% =====
% AXES: axes in which the markers are plotted.
% P: np x 2 or np x 3 matrix with the coordinates of the markers.
% COLOR: color of the markers.
% MARKER: type of the markers.
% MARKER_SIZE: size of the markers (default = 5).
%
% Output
% ======
% H: handle to the line plot object.
%
% See also
% ========
% RENDER_POINTS

if nargin < 5
  marker_size = 5;
end
if size(p, 2) == 2
  h = line('Parent', axes, ...
    'XData', p(:, 1), ...
    'YData', p(:, 2), ...
    'LineStyle', 'none', ...
    'MarkerFaceColor', color, ...
    'MarkerEdgeColor', color, ...
    'HitTest', 'off', ...    
    'Marker', marker, ...
    'MarkerSize', marker_size);
else
  h = line('Parent', axes, ...
    'XData', p(:, 1), ...
    'YData', p(:, 2), ...
    'ZData', p(:, 3), ...
    'LineStyle', 'none', ...
    'MarkerFaceColor', color, ...
    'MarkerEdgeColor', color, ...
    'HitTest', 'off', ...
    'Marker', marker, ...
    'MarkerSize', marker_size);
end
